version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    working_dir: /app
    command: python app.py

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
